import type { InitGatewayParam, InitGatewayModal, DeviceSystemModal, WifiLockServerInfo, CycleDateParam, ScanLockModal, ScanGatewayModal, ScanWifiModal, ScanRemoteKeyModal, ScanDoorSensorModal, ScanWirelessKeypadModal } from './types';
import { ConnectState, LockState, LockControlType, LockUnlockDirection, LockSoundVolume, LockConfigType, LockPassageMode, LockRecordType, LockAccessoryType, LiftWorkMode, BluetoothState, LockFunction } from './types';
export declare function startScanWirelessKeypad(callback?: (scanModal: ScanWirelessKeypadModal) => void): void;
export declare function stopScanWirelessKeypad(): void;
export declare function initWirelessKeypad(keypadMac: string, lockMac: string): Promise<[number, string]>;
export declare function startScanDoorSensor(callback?: (scanModal: ScanDoorSensorModal) => void): void;
export declare function stopScanDoorSensor(): void;
export declare function initDoorSensor(doorSensorMac: string, lockData: string): Promise<[number, string]>;
export declare function startScanRemoteKey(callback?: (scanModal: ScanRemoteKeyModal) => void): void;
export declare function stopScanRemoteKey(): void;
export declare function initRemoteKey(remoteMac: string, lockData: string): Promise<[number, string]>;
export declare function getRemoteKeySystemInfo(remoteMac: string): Promise<DeviceSystemModal>;
export declare function startScanGateway(callback?: (scanGatewayModal: ScanGatewayModal) => void): void;
export declare function stopScanGateway(): void;
export declare function connectGateway(mac: string): Promise<ConnectState>;
export declare function getNearbyWifi(progress?: (scanWifiModalList: ScanWifiModal[]) => void, finish?: () => void, fail?: (errorCode: number, description: string) => void): Promise<void>;
export declare function initGateway(params: InitGatewayParam): Promise<InitGatewayModal>;
export declare function startScan(callback?: (scanLockModal: ScanLockModal) => void): void;
export declare function stopScan(): void;
export declare function initLock(params: {
    lockMac: string;
    clientPara?: string;
}): Promise<string>;
export declare function getLockVersionWithLockMac(lockMac: string): Promise<string>;
export declare function getAccessoryElectricQuantity(accessoryType: LockAccessoryType, accessoryMac: string, lockData: string): Promise<[number, number]>;
export declare function resetLock(lockData: string): Promise<void>;
export declare function resetEkey(lockData: string): Promise<string>;
export declare function controlLock(control: LockControlType, lockData: string): Promise<[number, number, number]>;
export declare function createCustomPasscode(passcode: string, startDate: number, endDate: number, lockData: string): Promise<void>;
export declare function recoverPasscode(passcode: string, passcodeType: number, cycleType: number, startDate: number, endDate: number, lockData: string): Promise<void>;
export declare function modifyPasscode(passcodeOrigin: string, passcodeNew: string, startDate: number, endDate: number, lockData: string): Promise<void>;
export declare function deletePasscode(passcode: string, lockData: string): Promise<void>;
export declare function resetPasscode(lockData: string): Promise<string>;
export declare function getLockSwitchState(lockData: string): Promise<LockState>;
export declare function addCard(cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string, progress?: () => void): Promise<string>;
export declare function recoverCard(cardNumber: string, cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string): Promise<void>;
export declare function modifyCardValidityPeriod(cardNumber: string, cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string): Promise<void>;
export declare function deleteCard(cardNumber: string, lockData: string): Promise<void>;
export declare function clearAllCards(lockData: string): Promise<void>;
export declare function addFingerprint(cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string, progress?: (currentCount: number, totalCount: number) => void): Promise<string>;
export declare function modifyFingerprintValidityPeriod(fingerprintNumber: string, cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string): Promise<void>;
export declare function deleteFingerprint(fingerprintNumber: string, lockData: string): Promise<void>;
export declare function clearAllFingerprints(lockData: string): Promise<void>;
export declare function modifyAdminPasscode(adminPasscode: string, lockData: string): Promise<string>;
export declare function setLockTime(timestamp: number, lockData: string): Promise<void>;
export declare function getLockTime(lockData: string): Promise<number>;
export declare function getLockSystem(lockData: string): Promise<DeviceSystemModal>;
export declare function getLockElectricQuantity(lockData: string): Promise<number>;
export declare function getLockOperationRecord(type: LockRecordType, lockData: string): Promise<string>;
export declare function getLockAutomaticLockingPeriodicTime(lockData: string): Promise<[number, number, number]>;
export declare function setLockAutomaticLockingPeriodicTime(seconds: number, lockData: string): Promise<void>;
export declare function getLockRemoteUnlockSwitchState(lockData: string): Promise<boolean>;
export declare function setLockRemoteUnlockSwitchState(isOn: boolean, lockData: string): Promise<string>;
export declare function getLockConfig(config: LockConfigType, lockData: string): Promise<[number, boolean]>;
export declare function setLockConfig(config: LockConfigType, isOn: boolean, lockData: string): Promise<void>;
export declare function setLockSoundVolume(soundVolume: LockSoundVolume, lockData: string): Promise<void>;
export declare function getLockSoundVolume(lockData: string): Promise<LockSoundVolume>;
export declare function getUnlockDirection(lockData: string): Promise<LockUnlockDirection>;
export declare function setUnlockDirection(direction: LockUnlockDirection, lockData: string): Promise<void>;
export declare function setUnlockDirectionAutomatic(lockData: string): Promise<LockUnlockDirection>;
export declare function addPassageMode(mode: LockPassageMode, days: number[], startDate: number, endDate: number, lockData: string): Promise<void>;
export declare function clearAllPassageModes(lockData: string): Promise<void>;
export declare function addRemoteKey(remoteKeyMac: string, cycleDateList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string): Promise<void>;
export declare function modifyRemoteKey(remoteKeyMac: string, cycleDateList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string): Promise<void>;
export declare function deleteRemoteKey(remoteKeyMac: string, lockData: string): Promise<void>;
export declare function clearAllRemoteKey(lockData: string): Promise<void>;
export declare function addDoorSensor(doorSensorMac: string, lockData: string): Promise<void>;
export declare function clearAllDoorSensor(lockData: string): Promise<void>;
export declare function setDoorSensorAlertTime(time: number, lockData: string): Promise<void>;
export declare function scanWifi(lockData: string, callback?: (isFinished: boolean, wifiList: ScanWifiModal[]) => void, fail?: (errorCode: number, description: string) => void): Promise<void>;
export declare function configWifi(wifiName: string, wifiPassword: string, lockData: string): Promise<void>;
export declare function configServer(ip: string, port: string, lockData: string): Promise<void>;
export declare function getWifiInfo(lockData: string): Promise<[string, number]>;
export declare function configIp(info: WifiLockServerInfo, lockData: string): Promise<void>;
export declare function getWifiPowerSavingTime(lockData: string): Promise<string>;
export declare function configWifiPowerSavingTime(weekDays: number[], startDate: number, endDate: number, lockData: string): Promise<void>;
export declare function clearWifiPowerSavingTime(lockData: string): Promise<void>;
export declare function addFace(cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string, progress?: (state: number, faceErrorCode: number) => void): Promise<string>;
export declare function addFaceFeatureData(faceFeatureData: string, cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string): Promise<string>;
export declare function modifyFaceValidityPeriod(cycleList: CycleDateParam[] | null, startDate: number, endDate: number, faceNumber: string, lockData: string): Promise<void>;
export declare function deleteFace(faceNumber: string, lockData: string): Promise<void>;
export declare function clearFace(lockData: string): Promise<void>;
export declare function activateLiftFloors(floors: string, lockData: string): Promise<[number, number, number]>;
export declare function setLiftControlEnableFloors(floors: string, lockData: string): Promise<void>;
export declare function setLiftWorkMode(workMode: LiftWorkMode, lockData: string): Promise<void>;
export declare function getBluetoothState(): Promise<BluetoothState>;
export declare function supportFunction(lockFunction: LockFunction, lockData: string): Promise<boolean>;
export declare function addListener(eventName: string, listener: (eventName: string) => void): void;
export declare function removeListener(eventName: string, listener: (eventName: string) => void): void;
//# sourceMappingURL=core.d.ts.map