import type { AnyMap, HybridObject } from 'react-native-nitro-modules';
import type { InitGatewayParam, InitGatewayModal, DeviceSystemModal, WifiLockServerInfo, CycleDateParam, InitLockParam, NumberStringPair, NumberNumberPair, NumberNumberNumberTriple, NumberBooleanPair, StringNumberPair } from './types';
export interface TtlockNitro extends HybridObject<{
    ios: 'swift';
    android: 'kotlin';
}> {
    startScanWirelessKeypad(): void;
    stopScanWirelessKeypad(): void;
    initWirelessKeypad(keypadMac: string, lockMac: string, resolve: (data: NumberStringPair) => void, reject: (errorCode: number, description: string) => void): void;
    startScanDoorSensor(): void;
    stopScanDoorSensor(): void;
    initDoorSensor(doorSensorMac: string, lockData: string, resolve: (data: NumberStringPair) => void, reject: (errorCode: number, description: string) => void): void;
    startScanRemoteKey(): void;
    stopScanRemoteKey(): void;
    initRemoteKey(remoteMac: string, lockData: string, resolve: (data: NumberStringPair) => void, reject: (errorCode: number, description: string) => void): void;
    getRemoteKeySystemInfo(remoteMac: string, resolve: (data: DeviceSystemModal) => void, reject: (errorCode: number, description: string) => void): void;
    startScanGateway(): void;
    stopScanGateway(): void;
    connect(mac: string, resolve: (state: number) => void): void;
    getNearbyWifi(resolve: (state: number) => void): void;
    initGateway(params: InitGatewayParam, resolve: (data: InitGatewayModal) => void, reject: (errorCode: number) => void): void;
    startScan(): void;
    stopScan(): void;
    initLock(params: InitLockParam, resolve: (lockData: string) => void, reject: (errorCode: number, description: string) => void): void;
    getLockVersionWithLockMac(lockMac: string, resolve: (lockVersion: string) => void, reject: (errorCode: number, description: string) => void): void;
    getAccessoryElectricQuantity(accessoryType: number, accessoryMac: string, lockData: string, resolve: (data: NumberNumberPair) => void, reject: (errorCode: number, description: string) => void): void;
    resetLock(lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    resetEkey(lockData: string, resolve: (lockData: string) => void, reject: (errorCode: number, description: string) => void): void;
    controlLock(controlAction: number, lockData: string, resolve: (data: NumberNumberNumberTriple) => void, reject: (errorCode: number, description: string) => void): void;
    createCustomPasscode(passcode: string, startDate: number, endDate: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    recoverPasscode(passcode: string, passcodeType: number, cycleType: number, startDate: number, endDate: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    modifyPasscode(passcodeOrigin: string, passcodeNew: string, startDate: number, endDate: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    deletePasscode(passcode: string, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    resetPasscode(lockData: string, resolve: (lockData: string) => void, reject: (errorCode: number, description: string) => void): void;
    getLockSwitchState(lockData: string, resolve: (state: number) => void, reject: (errorCode: number, description: string) => void): void;
    addCard(cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string, resolve: (cardNumber: string) => void, reject: (errorCode: number, description: string) => void): void;
    recoverCard(cardNumber: string, cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    modifyCardValidityPeriod(cardNumber: string, cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    deleteCard(cardNumber: string, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    clearAllCards(lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    addFingerprint(cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string, resolve: (fingerprintNumber: string) => void, reject: (errorCode: number, description: string) => void): void;
    modifyFingerprintValidityPeriod(fingerprintNumber: string, cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    deleteFingerprint(fingerprintNumber: string, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    clearAllFingerprints(lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    modifyAdminPasscode(adminPasscode: string, lockData: string, resolve: (passcode: string) => void, reject: (errorCode: number, description: string) => void): void;
    setLockTime(timestamp: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    getLockTime(lockData: string, resolve: (lockTimestamp: string) => void, reject: (errorCode: number, description: string) => void): void;
    getLockSystem(lockData: string, resolve: (systemInfo: DeviceSystemModal) => void, reject: (errorCode: number, description: string) => void): void;
    getLockElectricQuantity(lockData: string, resolve: (electricQuantity: number) => void, reject: (errorCode: number, description: string) => void): void;
    getLockOperationRecord(type: number, lockData: string, resolve: (records: string) => void, reject: (errorCode: number, description: string) => void): void;
    getLockAutomaticLockingPeriodicTime(lockData: string, resolve: (data: NumberNumberNumberTriple) => void, reject: (errorCode: number, description: string) => void): void;
    setLockAutomaticLockingPeriodicTime(seconds: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    getLockRemoteUnlockSwitchState(lockData: string, resolve: (isOn: boolean) => void, reject: (errorCode: number, description: string) => void): void;
    setLockRemoteUnlockSwitchState(isOn: boolean, lockData: string, resolve: (lockData: string) => void, reject: (errorCode: number, description: string) => void): void;
    getLockConfig(config: number, lockData: string, resolve: (data: NumberBooleanPair) => void, reject: (errorCode: number, description: string) => void): void;
    setLockConfig(config: number, isOn: boolean, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    setLockSoundVolume(soundVolumeValue: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    getLockSoundVolume(lockData: string, resolve: (soundVolumeValue: number) => void, reject: (errorCode: number, description: string) => void): void;
    getUnlockDirection(lockData: string, resolve: (direction: number) => void, reject: (errorCode: number, description: string) => void): void;
    setUnlockDirection(direction: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    setUnlockDirectionAutomatic(lockData: string, resolve: (direction: number) => void, reject: (errorCode: number, description: string) => void): void;
    addPassageMode(type: number, weekly: number[] | null, monthly: number[] | null, startDate: number, endDate: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    clearAllPassageModes(lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    addRemoteKey(remoteMac: string, cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    modifyRemoteKey(remoteMac: string, cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    deleteRemoteKey(remoteMac: string, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    clearAllRemoteKey(lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    addDoorSensor(doorSensorMac: string, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    clearAllDoorSensor(lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    setDoorSensorAlertTime(time: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    scanWifi(lockData: string, reject: (errorCode: number, description: string) => void): void;
    configWifi(wifiName: string, wifiPassword: string, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    configServer(ip: string, port: string, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    getWifiInfo(lockData: string, resolve: (data: StringNumberPair) => void, reject: (errorCode: number, description: string) => void): void;
    configIp(info: WifiLockServerInfo, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    getWifiPowerSavingTime(lockData: string, resolve: (powerSavingData: string) => void, reject: (errorCode: number, description: string) => void): void;
    configWifiPowerSavingTime(days: number[] | null, startDate: number, endDate: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    clearWifiPowerSavingTime(lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    addFace(cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string, resolve: (faceNumber: string) => void, reject: (errorCode: number, description: string) => void): void;
    addFaceFeatureData(faceFeatureData: string, cycleList: CycleDateParam[] | null, startDate: number, endDate: number, lockData: string, resolve: (faceNumber: string) => void, reject: (errorCode: number, description: string) => void): void;
    modifyFaceValidityPeriod(cycleList: CycleDateParam[] | null, startDate: number, endDate: number, faceNumber: string, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    deleteFace(faceNumber: string, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    clearFace(lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    activateLiftFloors(floors: string, lockData: string, resolve: (data: NumberNumberNumberTriple) => void, reject: (errorCode: number, description: string) => void): void;
    setLiftControlEnableFloors(floors: string, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    setLiftWorkMode(workMode: number, lockData: string, resolve: () => void, reject: (errorCode: number, description: string) => void): void;
    getBluetoothState(resolve: (state: number) => void): void;
    supportFunction(lockFunction: number, lockData: string, resolve: (isSupport: boolean) => void): void;
    addListener(eventName: string, listener: (eventName: string, data: AnyMap | undefined) => void): void;
    removeListener(eventName: string, listener: (eventName: string, data: AnyMap | undefined) => void): void;
}
//# sourceMappingURL=TtlockNitro.nitro.d.ts.map